type: dnf
remove:
  packages:
    - firefox
    - firefox-langpacks
repos:
  files:
    - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
install:
  packages:
    - rsms-inter-fonts
    - adw-gtk3-theme

    - nm-connection-editor-desktop
    - tailscale
    - ddcutil
    - micro
