name: fedora-lenovo-cosmic
description: Customized Fedora COSMIC Atomic

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 44

modules:

  - from-file: shared/lenovo/config.yml
  - from-file: cosmic/lenovo/config.yml
