name: fedora-base-gnome
description: Custom Fedora GNOME image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41
alt-tags:
  - beta

modules:

  # Common
  - from-file: common/config.yml
  
  # GNOME
  - from-file: gnome-beta/config.yml
