name: fedora-base-gnome
description: Custom Fedora GNOME image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/lorduskordus/fedora-core-gnome
image-version: main-beta
alt-tags:
  - main-beta

modules:

  # Common
  - from-file: common/config.yml
  
  # GNOME
  - from-file: gnome-beta/config.yml
