type: dnf
remove:
  packages:
    - kate
    - kate-plugins
    - kate-krunner-plugin
repos:
  copr:
    # Includes Koi
    - birkch/Koi
install:
  packages:
    - Koi # Automatic themes switcher

    # KDE Calendar
    - merkuro
    - kdepim-addons  # For system integration
    - kdepim-runtime # For accounts support
    - qt6-qtlocation # Missing dependency
