modules:

  - from-file: common/config/kernel.yml
  - from-file: common/config/dnf.yml
  - from-file: common/config/flatpaks.yml
  - from-file: common/config/files.yml
  - from-file: common/config/justfiles.yml
  - from-file: common/config/hide-app-launchers.yml
  - from-file: common/config/scripts.yml
  - from-file: common/config/signing.yml
