modules:

  - from-file: common/config/kernel-coreos.yml
  - from-file: common/config/rpms.yml
  - from-file: common/config/flatpaks.yml
  - from-file: common/config/files.yml
  - from-file: common/config/justfiles.yml
  - from-file: common/config/hide-app-launchers.yml
  - from-file: common/config/systemd.yml
  - from-file: common/config/signing.yml
