modules:

  - type: rpm-ostree
    install:
      - adw-gtk3-theme
      - nm-connection-editor-desktop
      - rsms-inter-fonts
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (system)"
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.videolan.VLC
        - io.mpv.Mpv
        - org.gnome.Lollypop
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.SoundRecorder
        - io.github.dvlv.boxbuddyrs
        - io.github.flattool.Warehouse
        - org.gnome.Calculator
        - org.gnome.Papers
        - net.nokyan.Resources
        - com.tomjwatson.Emote
        - org.mozilla.Thunderbird
        - org.localsend.localsend_app
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-user
      repo-title: "Flathub"

  - type: files
    files:
      - source: system/common
        destination: /

  - type: justfiles
    validate: true
    include:
      - common

  - type: systemd # Copy services from systemd folder

  - type: signing
