name: fedora-base-cosmic
description: Custom Fedora COSMIC image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/ublue-os/cosmic
image-version: 41
alt-tags:
  - main

modules:

  # Common
  - from-file: common/config.yml
  
  # COSMIC
  - from-file: cosmic/config.yml
