name: fedora-base-cosmic
description: Custom Fedora COSMIC image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: 42

modules:

  # Common
  - from-file: common/config.yml
  
  # COSMIC
  - from-file: cosmic/config.yml
