name: fedora-base-cosmic
description: Custom Fedora COSMIC image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/lorduskordus/fedora-core-cosmic
image-version: coreos

modules:

  # Common
  - from-file: common/config.yml
  
  # COSMIC
  #- from-file: cosmic/config.yml
