name: fedora-base-kde
description: Custom Fedora KDE image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
alt-tags:
  - main

modules:

  # Kernel
  - from-file: kernel/main.yml

  # Common
  - from-file: common/config.yml

  # KDE
  - from-file: kde/config.yml
