name: fedora-base-kde
description: Custom Fedora KDE image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:

  # Common
  - from-file: common/kernel-coreos.yml
  - from-file: common/config.yml

  # KDE
  - from-file: kde/config.yml
