# ---------- CoreOS kernel ---------- #

# Get the kernel & NVIDIA akmods
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:coreos-stable-42 /rpms /kernel-rpms /tmp/akmods-rpms

# Install the kernel
RUN --mount=type=cache,dst=/var/cache/libdnf5 \
    --mount=type=cache,dst=/var/cache/rpm-ostree \

    echo "Installing CoreOS kernel" && \

    rpm --erase --nodeps \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra && \

    dnf5 -y install \
        /tmp/akmods-rpms/kernel-[0-9]*.rpm \
        /tmp/akmods-rpms/kernel-core-*.rpm \
        /tmp/akmods-rpms/kernel-modules-*.rpm \
        /tmp/akmods-rpms/kernel-devel-*.rpm && \

    dnf5 versionlock add \
        kernel \
        kernel-core \
        kernel-modules \
        kernel-modules-core \
        kernel-modules-extra \
        kernel-devel \
        kernel-devel-matched
