type: default-flatpaks
configurations:
  - scope: system
    notify: false
    install:
      - com.mattjakeman.ExtensionManager
      - com.github.tchx84.Flatseal
      - org.gnome.Calendar
      - org.gnome.FileRoller
      - org.gnome.Weather
      - org.gnome.baobab
      - org.gnome.clocks
