type: gnome-extensions
install:
  - ArcMenu
  - Legacy (GTK3) Theme Scheme Auto Switcher
  - Night Theme Switcher
  - Tiling Assistant
  - Just Perfection
  - Dash to Panel # Temporary before RPM comes
  #- Pano - Clipboard Manager
