type: rpm-ostree
remove:
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-window-list

  - gnome-classic-session
  - gnome-tour
  - gnome-system-monitor
replace:
  # Install triple buffering patch
  - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
    packages:
      - gnome-shell
      - mutter
      - mutter-common
repos:
  # Includes nautilus-admin
  - https://copr.fedorainfracloud.org/coprs/tomaszgasior/mushrooms/repo/fedora-%OS_VERSION%/tomaszgasior-mushrooms-fedora-%OS_VERSION%.repo
  # Includes morewaita-icon-theme
  - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
install:
  #- gnome-shell-extension-dash-to-panel # Temporarily replace by fork (files module handles it)
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-caffeine
  # Needed for Pano clipboard
  - libgda
  - libgda-sqlite

  - nautilus-admin
  - morewaita-icon-theme
  - firewall-config
  - dconf-editor
  - gnome-text-editor
