type: dnf
remove:
  packages:
    - firefox
    - firefox-langpacks

    - fedora-third-party
    - fedora-flathub-remote
    - fedora-workstation-repositories
repos:
  files:
    - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  copr:
    - alternateved/eza
install:
  packages:
    - rsms-inter-fonts
    - adw-gtk3-theme

    # Virtualization support
    - qemu     # Pulls 'edk2-ovmf' as dependency
    - libvirt  # Pulls 'libvirt-daemon-config-network' as dependency

    - micro
    - fish
    - bat
    - eza

    - ddcutil

    - nm-connection-editor-desktop
    - nextcloud-client
    - tailscale
