modules:

  - type: rpm-ostree
    repos:
      # COPR for morewaita-icon-theme
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes.repo
    install:
      - adw-gtk3-theme
      - morewaita-icon-theme
      - intel-gpu-tools
      - nm-connection-editor-desktop
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (systém)"
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-user
      repo-title: "Flathub (uživatel)"

  - type: bling
    install:
      - ublue-update

  - type: files
    files:
      - common/usr: /usr

  - type: fonts
    fonts:
      google-fonts:
        - Inter

  - type: systemd
    user:
      enabled:
        - podman.socket

  - type: signing