modules:

  - type: rpm-ostree
    repos:
      # COPR for nautilus-admin, enables shortcut 'Open as Admin' in Nautilus.
      - https://copr.fedorainfracloud.org/coprs/tomaszgasior/mushrooms/repo/fedora-%OS_VERSION%/tomaszgasior-mushrooms.repo
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-caffeine
      - firewall-config
      - nautilus-admin # Enables shortcut 'Open as Admin' in Nautilus.
    remove:
      - gnome-tour
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-window-list
      - gnome-classic-session

  - type: default-flatpaks
    system:
      install:
        # ------ Common ------ #
        - org.freedesktop.Platform.ffmpeg-full/x86_64/23.08
        - org.freedesktop.Platform.VAAPI.Intel/x86_64/23.08
        - org.freedesktop.Platform.VaInfo/x86_64/23.08
        - org.winehq.Wine//stable-23.08
        - org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
        - org.mozilla.firefox
        - org.onlyoffice.desktopeditors
        - org.videolan.VLC
        - io.mpv.Mpv
        - org.gnome.Lollypop
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.SoundRecorder
        - com.github.marhkb.Pods
        - io.github.flattool.Warehouse
        - org.gnome.Calculator
        - org.gnome.Evince
        - org.gnome.TextEditor
        - net.nokyan.Resources
        - com.tomjwatson.Emote
        # ------ GNOME ------ #
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - org.gnome.Calendar
        - org.gnome.Extensions
        - org.gnome.FileRoller
        - org.gnome.Geary
        - org.gnome.NautilusPreviewer
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks

  - type: bling
    install:
      - dconf-update-service

  - type: files
    files:
      - gnome/usr: /usr

  - type: script
    scripts:
      - gnome/custom-dash-to-panel.sh

  # Apply the triple buffer patch.
  - type: rpm-ostree-override
    repo:
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched.repo
    replace:
      - mutter
      - mutter-common  