modules:

  - type: rpm-ostree
    repos:
      # COPR for Koi, switch between light & dark themes.
      - https://copr.fedorainfracloud.org/coprs/birkch/Koi/repo/fedora-%OS_VERSION%/birkch-Koi-fedora.repo
    install:
      - Koi # For switching between light & dark themes.
      - kalendar
      - kdepim-addons
    remove:
      - filelight
      - kate
      - kate-plugins
      - kfind
      - kcharselect
      - kmousetool

  - type: default-flatpaks
    system:
      install:
        # ------ Common ------ #
        - org.freedesktop.Platform.ffmpeg-full/x86_64/23.08
        - org.freedesktop.Platform.VAAPI.Intel/x86_64/23.08
        - org.freedesktop.Platform.VaInfo/x86_64/23.08
        - org.winehq.Wine//stable-23.08
        - org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
        - org.mozilla.firefox
        - org.onlyoffice.desktopeditors
        - org.videolan.VLC
        - io.mpv.Mpv
        - org.gnome.Lollypop
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.SoundRecorder
        - com.github.marhkb.Pods
        - io.github.flattool.Warehouse
        - org.gnome.Calculator
        - org.gnome.Evince
        - org.gnome.TextEditor
        - net.nokyan.Resources
        - com.tomjwatson.Emote
        # ------ KDE ------ #
        - org.kde.krdc
        - org.kde.filelight
        - org.kde.kclock
        - org.kde.kweather
        #- org.kde.ark
        #- org.kde.kalk
        #- org.kde.okular
        #- org.kde.elisa
        #- org.kde.kwrite