# Install Bazzite kernel
COPY --from=ghcr.io/ublue-os/bazzite-kernel:41 /tmp/rpms /tmp/bazzite-rpms
COPY --from=ghcr.io/ublue-os/akmods-nvidia-open:bazzite-41 /rpms /tmp/akmods-rpms
RUN --mount=type=cache,dst=/var/cache/rpm-ostree \
    
    echo "Installing Bazzite kernel" && \
    
    rpm-ostree cliwrap install-to-root / && \
    rpm-ostree override replace --experimental \
    /tmp/bazzite-rpms/kernel-[0-9]*.rpm \
    /tmp/bazzite-rpms/kernel-core-*.rpm \
    /tmp/bazzite-rpms/kernel-modules-*.rpm
