type: dnf
repos:
  cleanup: true
  files:
    - https://download.docker.com/linux/fedora/docker-ce.repo
    - https://download.opensuse.org/repositories/home:mkittler/Fedora_%OS_VERSION%/home:mkittler.repo
install:
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

    - podman-compose

    - syncthing
    - syncthingtray
