name: fedora-next-cosmic
description: Customized Fedora COSMIC Atomic

base-image: ghcr.io/ublue-os/base-main
image-version: 43

modules:

  - from-file: next/common/config.yml
  - from-file: next/cosmic/config.yml
