name: fedora-next-kde
description: Customized Fedora KDE Atomic

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:

  - from-file: next/common/config.yml
  - from-file: next/kde/config.yml

  # Temporarily install COSMIC DE
  - from-file: next/addons/cosmic-desktop.yml
