type: rpm-ostree
remove:
  - kate
  - kate-plugins
  - kate-krunner-plugin
  - kcharselect
repos:
  # Includes Koi
  - https://copr.fedorainfracloud.org/coprs/birkch/Koi/repo/fedora-%OS_VERSION%/birkch-Koi-fedora-%OS_VERSION%.repo
install:
  - Koi
  - merkuro # KDE Calendar
  - kdepim-addons # KDE Calendar system integration
  - kdepim-runtime # Needed for adding accounts in the KDE Calendar
