name: fedora-lenovo-kde
description: Customized Fedora KDE Atomic

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:

  - from-file: shared/lenovo/config.yml
  - from-file: kde/lenovo/config.yml
