name: fedora-base-kde-nvidia
description: Custom Fedora KDE image based on uBlue, built with BlueBuild. (Base, with NVIDIA support)

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 40

modules:

  # Common
  - from-file: image_configs/common.yml

  # KDE
  - from-file: image_configs/kde.yml