name: fedora-base-gnome-nvidia
description: Custom Fedora GNOME image based on uBlue, built with BlueBuild. (Base, with NVIDIA support)

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39

modules:

  # Common
  - from-file: image_configs/common.yml
  
  # GNOME
  - from-file: image_configs/gnome.yml