modules:

  - type: rpm-ostree
    repos:
      # COPR for nautilus-admin, enables shortcut 'Open as Admin' in Nautilus
      - https://copr.fedorainfracloud.org/coprs/tomaszgasior/mushrooms/repo/fedora-%OS_VERSION%/tomaszgasior-mushrooms-fedora-%OS_VERSION%.repo
      # COPR for morewaita-icon-theme
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-caffeine
      - firewall-config
      - nautilus-admin
      - morewaita-icon-theme
      # Needed for Pano clipboard
      - libgda
      - libgda-sqlite
    remove:
      - gnome-tour
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-window-list
      - gnome-session-xsession
      - gnome-classic-session
      - gnome-classic-session-xsession
    # Apply the triple buffer patch.
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - gnome-shell
          - mutter
          - mutter-common
          - xorg-x11-server-Xwayland
          - gdm

  - type: default-flatpaks
    system:
      install:
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - org.gnome.Calendar
        - org.gnome.FileRoller
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.TextEditor

  - type: bling
    install:
      - dconf-update-service

  - type: files
    files:
      - source: system/gnome
        destination: /

  - type: justfiles
    validate: true
    include:
      - gnome

  - type: script
    scripts:
      - gnome/custom-dash-to-panel.sh

  - type: gnome-extensions
    install:
      - ArcMenu
      - Legacy (GTK3) Theme Scheme Auto Switcher
      - Night Theme Switcher
      - Tiling Assistant
      #- Pano - Clipboard Manager # Enable when pushed to EGO
