modules:

  - from-file: gnome/config/triple-buffering-patch.yml
  - from-file: gnome/config/rpms.yml
  - from-file: gnome/config/flatpaks.yml
  - from-file: gnome/config/files.yml
  - from-file: gnome/config/justfiles.yml
  - from-file: gnome/config/gnome-extensions.yml
  - from-file: gnome/config/dconf-update.yml
