modules:

  - from-file: gnome/modules/triple_buffering_patch.yml
  - from-file: gnome/modules/rpm-ostree.yml
  - from-file: gnome/modules/default_flatpaks.yml
  - from-file: gnome/modules/files.yml
  - from-file: gnome/modules/justfiles.yml
  - from-file: gnome/modules/gnome_extensions.yml
  - from-file: gnome/modules/add_dconf_update_service.yml
