type: dnf
group-install:
  packages:
    - cosmic-desktop
install:
  packages:
    # Missing in 'cosmic-desktop'
    - cosmic-monitor

    # Missing dependencies
    - gvfs-mtp
    - gvfs-afc
    - gvfs-gphoto2
