type: dnf
repos:
  cleanup: true
  copr:
    - kordus/cosmic-applets
    - kordus/cosmic-apps
install:
  packages:
    - cosmic-ext-applet-clipboard-manager
    - cosmic-applet-clippy-land
    - snappea
