type: dnf
repos:
  cleanup: true
  copr:
    - kordus/cosmic-applets
install:
  packages:
    # Clipboard Manager RPMs from my COPR
    - cosmic-ext-applet-clipboard-manager
    - cosmic-applet-clippy-land
