type: default-flatpaks
configurations:
  - scope: user
    notify: false
    repo:
      url: https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
      name: cosmic
      title: COSMIC
  - scope: system
    notify: false
    repo:
      url: https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
      name: cosmic
      title: COSMIC
    install:
      # Basics
      # - dev.edfloreshz.Calculator

      # Recording
      # - io.github.cosmic_utils.camera

      # System
      - dev.edfloreshz.CosmicTweaks

      # Applets
      - io.github.cosmic_utils.cosmic-ext-applet-external-monitor-brightness
      - dev.DBrox.CosmicPrivacyIndicator
      - io.github.cosmic_utils.weather-applet
