name: fedora-next-kde-nvidia
description: Customized Fedora KDE Atomic

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

modules:

  - from-file: shared/next/config.yml
  - from-file: kde/next/config.yml

  # Temporarily install COSMIC DE
  - from-file: cosmic/base/config.yml
