type: dnf
remove:
  packages:
    # Has a bug where files are not opened in tabs
    # and one editor is enough
    - kwrite
repos:
  cleanup: true
  copr:
    - birkch/Koi
    - matinlotfali/KDE-Rounded-Corners
    - infinality/kwin-effects-better-blur-dx
install:
  packages:
    - Koi # Automatic theme switcher
    - kwin-effect-roundcorners
    - kwin-effects-better-blur-dx

    # KDE Calendar
    - merkuro
    - kdepim-addons   # System integration
    - kdepim-runtime  # Accounts support
