type: dnf
remove:
  packages:
    - firefox
    - firefox-langpacks
install:
  packages:
    - adw-gtk3-theme
    - rsms-inter-fonts

    # Virtualization
    - edk2-ovmf
    - qemu
    - libvirt

    - nm-connection-editor-desktop
    - micro
