type: default-flatpaks
configurations:
  - scope: user
    notify: false
    repo:
      url: https://dl.flathub.org/repo/flathub.flatpakrepo
      name: flathub
      title: Flathub
  - scope: system
    notify: false
    repo:
      url: https://dl.flathub.org/repo/flathub.flatpakrepo
      name: flathub
      title: Flathub
    install:
      # Basics
      - org.gnome.Calculator
      - org.gnome.clocks

      # App management
      - net.nokyan.Resources
      - it.mijorus.gearlever
      - com.ranfdev.DistroShelf
      - io.github.flattool.Warehouse
      - com.github.tchx84.Flatseal

      # Internet & Communication
      - com.brave.Browser
      - eu.betterbird.Betterbird
      - org.localsend.localsend_app

      # Documents
      - org.onlyoffice.desktopeditors
      - org.gnome.Papers

      # Media
      - org.videolan.VLC
      - io.mpv.Mpv
      - org.gnome.Lollypop
      - org.gnome.Loupe

      # Recording
      - org.gnome.Snapshot
      - org.gnome.SoundRecorder
