modules:

  - type: rpm-ostree
    install:
      - adw-gtk3-theme
      - rsms-inter-fonts

      - nm-connection-editor-desktop
      - micro

  - type: script
    snippets:
      - "dnf5 -y remove firefox firefox-langpacks"
