modules:

  - from-file: base/common/config/kernel.yml
  - from-file: base/common/config/kargs.yml
  - from-file: base/common/config/dnf.yml
  - from-file: base/common/config/brew.yml
  - from-file: base/common/config/flatpaks.yml
  - from-file: base/common/config/files.yml
  - from-file: base/common/config/justfiles.yml
  - from-file: base/common/config/hide-app-launchers.yml
  - from-file: base/common/config/services.yml
  - from-file: base/common/config/scripts.yml
  - from-file: base/common/config/signing.yml
