name: fedora-next-cosmic-nvidia
description: Customized Fedora COSMIC Atomic

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 44

modules:

  - from-file: shared/next/config.yml
  - from-file: cosmic/next/config.yml
