type: dnf
source: ghcr.io/blue-build/modules/dnf:dnf-module
repos:
  copr:
    - wiiznokes/cosmic-applets-unofficial
install:
  packages:
    - cosmic-ext-applet-clipboard-manager
    - cosmic-ext-applet-external-monitor-brightness
    - tuned # This is missing for some reason
