name: fedora-base-kde
description: Custom Fedora KDE image based on uBlue, built with BlueBuild. (Base)

base-image: ghcr.io/lorduskordus/fedora-core-kde
image-version: main-beta
alt-tags:
  - main-beta

modules:

  # Common
  - from-file: common/config.yml

  # KDE
  - from-file: kde/config.yml
