set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/usr/share/ublue-os/just/15-luks.just"
import "/usr/share/ublue-os/just/20-clean.just"
import "/usr/share/ublue-os/just/59-saved.just"     # Handpicked commands from excluded .just files
import "/usr/share/ublue-os/just/60-custom.just"
