name: fedora-base-cosmic
description: Customized Fedora COSMIC Atomic

base-image: ghcr.io/ublue-os/base-main
image-version: 43

modules:

  - from-file: base/common/config.yml
  - from-file: base/cosmic/config.yml
