modules:

  - from-file: base/common/config.yml

  - from-file: next/common/config/dnf.yml
  - from-file: next/common/config/files.yml
  - from-file: next/common/config/justfiles.yml
  - from-file: next/common/config/services.yml
  - from-file: next/common/config/scripts.yml
