name: Template - Build Desktop

on:
  workflow_call:
    inputs:
      desktop:
        required: true
        type: string

jobs:
  base:
    name: Base
    uses: ./.github/workflows/template-build-image.yml
    secrets: inherit
    with:
      pretty_name: "Base"
      recipe: ${{ inputs.desktop }}/base/recipe.yml

  next:
    name: Next
    uses: ./.github/workflows/template-build-image.yml
    secrets: inherit
    with:
      pretty_name: "Next"
      recipe: ${{ inputs.desktop }}/next/recipe.yml
