name: Template - Build Desktop

on:
  workflow_call:
    inputs:
      desktop:
        required: true
        type: string

jobs:
  lenovo:
    name: Lenovo
    uses: ./.github/workflows/template-build-image.yml
    secrets: inherit
    with:
      pretty_name: "Lenovo"
      recipe: ${{ inputs.desktop }}/lenovo/recipe.yml

  next-nvidia:
    name: Next
    uses: ./.github/workflows/template-build-image.yml
    secrets: inherit
    with:
      pretty_name: "Next (NVIDIA)"
      recipe: ${{ inputs.desktop }}/next/recipe.yml
